<?php

/**
 * BasesfVkontakteUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $settings
 * @property datetime $fetched_at
 * @property Doctrine_Collection $Friends
 * 
 * @method integer             getSettings()   Returns the current record's "settings" value
 * @method datetime            getFetchedAt()  Returns the current record's "fetched_at" value
 * @method Doctrine_Collection getFriends()    Returns the current record's "Friends" collection
 * @method sfVkontakteUser     setSettings()   Sets the current record's "settings" value
 * @method sfVkontakteUser     setFetchedAt()  Sets the current record's "fetched_at" value
 * @method sfVkontakteUser     setFriends()    Sets the current record's "Friends" collection
 * 
 * @package    vkontakte_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfVkontakteUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_vkontakte_user');
        $this->hasColumn('settings', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fetched_at', 'datetime', null, array(
             'type' => 'datetime',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfVkontakteUser as Friends', array(
             'refClass' => 'sfVkontakteFriendship',
             'local' => 'user_from',
             'foreign' => 'user_to',
             'equal' => true));

        $sfvkontakteapiuser0 = new sfVkontakteApiUser(array(
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($sfvkontakteapiuser0);
        $this->actAs($timestampable0);
    }
}