<?php

/**
 * BasesfVkontakteFriendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_from
 * @property integer $user_to
 * 
 * @method integer               getUserFrom()  Returns the current record's "user_from" value
 * @method integer               getUserTo()    Returns the current record's "user_to" value
 * @method sfVkontakteFriendship setUserFrom()  Sets the current record's "user_from" value
 * @method sfVkontakteFriendship setUserTo()    Sets the current record's "user_to" value
 * 
 * @package    vkontakte_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfVkontakteFriendship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_vkontakte_friendship');
        $this->hasColumn('user_from', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_to', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}